const allStocks = [
  {
    name: "Tata Motors",
    symbol: "TATAMOTORS",
    logo: "https://logo.clearbit.com/tatamotors.com",
    price: 920.5,
    change: "+25.40",
    percent: "+2.84%",
    sector: "Automobile",
    up: true,
  },
  {
    name: "Infosys",
    symbol: "INFY",
    logo: "https://logo.clearbit.com/infosys.com",
    price: 1420.75,
    change: "+35.10",
    percent: "+2.54%",
    sector: "IT",
    up: true,
  },
  {
    name: "ITC Limited",
    symbol: "ITC",
    logo: "https://logo.clearbit.com/itcportal.com",
    price: 425.3,
    change: "-12.40",
    percent: "-2.83%",
    sector: "FMCG",
    up: false,
  },
  {
    name: "HDFC Bank",
    symbol: "HDFCBANK",
    logo: "https://logo.clearbit.com/hdfcbank.com",
    price: 1620.2,
    change: "+28.65",
    percent: "+1.80%",
    sector: "Banking",
    up: true,
  },
  {
    name: "Adani Ports",
    symbol: "ADANIPORTS",
    logo: "https://logo.clearbit.com/adani.com",
    price: 1010.2,
    change: "-29.10",
    percent: "-2.80%",
    sector: "Infrastructure",
    up: false,
  },
  {
    name: "Wipro",
    symbol: "WIPRO",
    logo: "https://logo.clearbit.com/wipro.com",
    price: 520.4,
    change: "+14.20",
    percent: "+2.80%",
    sector: "IT",
    up: true,
  },
  {
    name: "Mahindra & Mahindra",
    symbol: "M&M",
    logo: "https://logo.clearbit.com/mahindra.com",
    price: 1840.95,
    change: "+40.00",
    percent: "+2.22%",
    sector: "Automobile",
    up: true,
  },

  {
    name: "Power Grid Corp",
    symbol: "POWERGRID",
    logo: "https://logo.clearbit.com/powergrid.in",
    price: 250.85,
    change: "-6.30",
    percent: "-2.45%",
    sector: "Utilities",
    up: false,
  },
  {
    name: "Tata Steel",
    symbol: "TATASTEEL",
    logo: "https://logo.clearbit.com/tatasteel.com",
    price: 125.1,
    change: "-3.20",
    percent: "-2.49%",
    sector: "Metals",
    up: false,
  },
  {
    name: "Bajaj Finance",
    symbol: "BAJFINANCE",
    logo: "https://logo.clearbit.com/bajajfinserv.in",
    price: 6150.45,
    change: "-180.75",
    percent: "-2.86%",
    sector: "Finance",
    up: false,
  },
  {
    name: "Reliance Industries",
    symbol: "RELIANCE",
    logo: "https://logo.clearbit.com/ril.com",
    price: 2785.3,
    change: "+22.15",
    percent: "+0.80%",
    sector: "Conglomerate",
    up: true,
  },
  {
    name: "HCL Technologies",
    symbol: "HCLTECH",
    logo: "https://logo.clearbit.com/hcltech.com",
    price: 1320.0,
    change: "+18.60",
    percent: "+1.43%",
    sector: "IT",
    up: true,
  },
  {
    name: "Tech Mahindra",
    symbol: "TECHM",
    logo: "https://logo.clearbit.com/techmahindra.com",
    price: 1235.75,
    change: "+16.25",
    percent: "+1.33%",
    sector: "IT",
    up: true,
  },
  {
    name: "Asian Paints",
    symbol: "ASIANPAINT",
    logo: "https://logo.clearbit.com/asianpaints.com",
    price: 3010.6,
    change: "-45.60",
    percent: "-1.49%",
    sector: "Chemicals",
    up: false,
  },
  {
    name: "Maruti Suzuki",
    symbol: "MARUTI",
    logo: "https://logo.clearbit.com/marutisuzuki.com",
    price: 9700.85,
    change: "+110.25",
    percent: "+1.15%",
    sector: "Automobile",
    up: true,
  },
  {
    name: "Hindustan Unilever",
    symbol: "HINDUNILVR",
    logo: "https://logo.clearbit.com/hul.co.in",
    price: 2510.0,
    change: "-30.50",
    percent: "-1.20%",
    sector: "FMCG",
    up: false,
  },
  {
    name: "State Bank of India",
    symbol: "SBIN",
    logo: "https://logo.clearbit.com/sbi.co.in",
    price: 630.75,
    change: "+8.30",
    percent: "+1.33%",
    sector: "Banking",
    up: true,
  },
  {
    name: "Coal India",
    symbol: "COALINDIA",
    logo: "https://logo.clearbit.com/coalindia.in",
    price: 295.5,
    change: "-4.10",
    percent: "-1.37%",
    sector: "Energy",
    up: false,
  },
  {
    name: "NTPC",
    symbol: "NTPC",
    logo: "https://logo.clearbit.com/ntpc.co.in",
    price: 320.8,
    change: "+5.50",
    percent: "+1.75%",
    sector: "Utilities",
    up: true,
  },
  {
    name: "Larsen & Toubro",
    symbol: "LT",
    logo: "https://logo.clearbit.com/lntecc.com",
    price: 3510.9,
    change: "+60.70",
    percent: "+1.76%",
    sector: "Infrastructure",
    up: true,
  },
];

export { allStocks };
