const topGainers = [
  {
    name: "Tata Motors",
    symbol: "TATAMOTORS",
    logo: "https://logo.clearbit.com/tatamotors.com",
    value: 920.5,
    change: "+25.40",
    percent: "+2.84%",
    up: true,
  },
  {
    name: "Infosys",
    symbol: "INFY",
    logo: "https://logo.clearbit.com/infosys.com",
    value: 1420.75,
    change: "+35.10",
    percent: "+2.54%",
    up: true,
  },
  {
    name: "HDFC Bank",
    symbol: "HDFCBANK",
    logo: "https://logo.clearbit.com/hdfcbank.com",
    value: 1620.2,
    change: "+28.65",
    percent: "+1.80%",
    up: true,
  },
  {
    name: "Wipro",
    symbol: "WIPRO",
    logo: "https://logo.clearbit.com/wipro.com",
    value: 520.4,
    change: "+14.20",
    percent: "+2.80%",
    up: true,
  },
  {
    name: "Mahindra & Mahindra",
    symbol: "M&M",
    logo: "https://logo.clearbit.com/mahindra.com",
    value: 1840.95,
    change: "+40.00",
    percent: "+2.22%",
    up: true,
  },
];

const topLosers = [
  {
    name: "ITC Limited",
    symbol: "ITC",
    logo: "https://logo.clearbit.com/itcportal.com",
    value: 425.3,
    change: "-12.40",
    percent: "-2.83%",
    up: false,
  },
  {
    name: "Adani Ports",
    symbol: "ADANIPORTS",
    logo: "https://logo.clearbit.com/adani.com",
    value: 1010.2,
    change: "-29.10",
    percent: "-2.80%",
    up: false,
  },
  {
    name: "Power Grid Corp",
    symbol: "POWERGRID",
    logo: "https://logo.clearbit.com/powergrid.in",
    value: 250.85,
    change: "-6.30",
    percent: "-2.45%",
    up: false,
  },
  {
    name: "Tata Steel",
    symbol: "TATASTEEL",
    logo: "https://logo.clearbit.com/tatasteel.com",
    value: 125.1,
    change: "-3.20",
    percent: "-2.49%",
    up: false,
  },
  {
    name: "Bajaj Finance",
    symbol: "BAJFINANCE",
    logo: "https://logo.clearbit.com/bajajfinserv.in",
    value: 6150.45,
    change: "-180.75",
    percent: "-2.86%",
    up: false,
  },
];

export { topGainers, topLosers };
